#
###################################
# Site wide configuration
####################################
#
title: Mukesh Thawani
email:
description: Hi, This is Mukesh Thawani.
url: "https://mukeshthawani.com"


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title

exclude:           [vendor]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Mukesh Thawani"
  avatar: avatar.png
  job:
  bio: "iOS Developer, Swift enthusiast"
  email: mukesh9039@gmail.com
  disqus-shortname:
  twitter: MukeshThawani
  facebook: #username
  google:
    plus: #username
    analytics: UA-106952527-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mukeshthawani
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: mukeshthawani
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
